name: Erik Schwartz
description: "Erik Schwartz's blog, projects, and vine"
url: http://erikschwartz.net
permalink: /slug/
paginate: 10
exclude: [Gemfile, Gemfile.lock, Rakefile, config.rb, CNAME]
prose:
  rooturl: "_posts"
  siteurl: "http://erikschwartz.net/"
  media: "images"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "date"
        field:
          element: "text"
          placeholder: "date"
          label: "date"
      - name: "permalink"
        field:
          element: "text"
          placeholder: "permalink"
          label: "permalink"
      - name: "Title"
        field:
          element: "text"
          placeholder: "title"
          label: "title"
      - name: "category"
        field:
          element: "select"
          label: "Category"
          placeholder: "Category"
          options:
            - name: "projects"
              value: "projects"
            - name: "vine"
              value: "vine"
            - name: "blog"
              value: "blog"
      - name: "current-tab"
        field:
          element: "select"
          label: "Current Tab"
          placeholder: "Current Tab"
          options:
            - name: "projects"
              value: "projects"
            - name: "vine"
              value: "vine"
            - name: "blog"
              value: "blog"
      - name: "author"
        field:
          element: "select"
          label: "Author"
          placeholder: "Author"
          options:
            - name: "Erik Schwartz"
              value: "Erik Schwartz"
