name: Erik Schwartz
description: "Erik Schwartz's blog, projects, and vine"
url: http://erikschwartz.net
permalink: /slug/
paginate: 5
exclude: [Gemfile, Gemfile.lock, Rakefile, config.rb]
markdown: redcarpet
gems: [jekyll-paginate]
