name: Erik Schwartz
description: "Erik Schwartz's blog, projects, and vine"
url: https://erikschwartz.net
permalink: /slug/
paginate: 5
exclude: [Gemfile, Gemfile.lock, Rakefile, config.rb]
gems: [jekyll-paginate]
prose:
  media: 'images'
